#! /bin/sh

# autostart services
killall -9 sxhkd ksuperkey
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
ksuperkey &
~/.config/polybar/launch.sh

# color settings
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# bspwm settings
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# window rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Emacs state=tiled desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a Gthumb state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
